### ISSUE TITLE
What's the deal with the seductive lady?

### ISSUE THREAD

**Issue by OndrejPopp** [mltframework/shotcut_web#4]
Hi. I was just looking at the Shotcut website. One thing that cought my eye if I may say so is the main picture of the lady from behind taking off her bra.. or whatever?

I am thinking that if you value this product maybe you should use an other picture for your website. Meaning, is this website about a great video editor or about ladies taking off their bras or whatever.

Kind regards,
Ondrej Popp

**Comment by ddennedy** [comment]
Nothing subversive or disrespectful intended. It just happened to be an image I was working with while working on color grading capabilities that went into a screenshot. I have been meaning to change that whole image because I think it looks a little cheesy and amateur. This was my nudge to follow through on it.

**Comment by OndrejPopp** [comment]
Ok. Cool. Have a great day.
